import = [
  "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[shell] 
program = "/home/anthonyoon/.cargo/bin/nu"

[env]
TERM = "xterm-256color"

[font.normal]
family = "SpaceMono Nerd Font Mono"
style = "Regular"
