theme = "kanagawa"

[editor]
scroll-lines = 1
cursorline = true
true-color = true
color-modes = true
line-number = "relative"
shell = ["bash"]
auto-completion = true
auto-info = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "file-modification-indicator"]
center = ["diagnostics", "workspace-diagnostics"]
right = ["selections", "spacer", "version-control", "position"]

[editor.lsp]
enable = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true

[editor.indent-guides]
render = true
character = "|"

[keys.normal]
# Flip anchor and cursor
space.space = "flip_selections"
space.c = "toggle_comments"
