
[language-server.rust-analyzer]
command = "rust-analyzer"
config = { cargo.features = "all", rust-analyzer.check.command = "clippy"}

[[language]]
name = "rust"
language-id = "rust"
file-types = ["rs"]
comment-token = "//"
indent = { tab-width = 2, unit = " " }
formatter = { command = "rustfmt"}
language-servers = ["rust-analyzer"]
roots = ["Cargo.lock"]
